# Generated by Django 5.1.7 on 2025-11-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='template',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
