# Generated by Django 5.1.7 on 2025-11-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpost_template_delete_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_file_path',
            field=models.FilePathField(blank=True, match='*.html', path='C:\\Users\\ziade\\Desktop\\Personal Repos\\Portifolio\\portifolio-mlziade\\blog\\files\\posts'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
