# Generated by Django 5.1.7 on 2025-11-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content_file_path',
            field=models.FilePathField(blank=True, match='.*\\.md$', path='C:\\Users\\ziade\\Desktop\\Personal Repos\\Portifolio\\portifolio-mlziade\\blog\\files\\posts'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='Filename from blog/files/thumbnails/', max_length=255, null=True),
        ),
    ]
